### ISSUE TITLE
Styles: Using variables for colors/shared properties

### ISSUE THREAD

**Issue by olivierobert** [ericparklondon/nimbl3#3]
![eric___volumes_workspace__candidates-tests_eric__-_____src_components_searchbar_styles_scss__eric_](https://user-images.githubusercontent.com/696529/41531955-54c26a20-731f-11e8-8d72-cee55c860424.png)

All CSS properties values are hard-coded. In a small project, this might work but in any fairly medium size project, this is going to cause maintenance issues and slow down development.

> I also noticed that `height` is defined twice for `search-section`

**Comment by ericparklondon** [comment]
I wish I would have spotted that height defined twice before :(

I was having some weird issues with it but couldn't figure out why.
