### ISSUE TITLE
Why using IDs over CSS classes?

### ISSUE THREAD

**Issue by olivierobert** [ericparklondon/nimbl3#5]
![eric_park](https://user-images.githubusercontent.com/696529/41532423-1e265ba0-7321-11e8-9118-ebbb51cf9f99.png)

Due to the CSS specificity tree, it's usually recommended to limit usage of IDs but instead rely almost exclusively on class names for styling.

**Comment by ericparklondon** [comment]
I mainly did it to reinforce the fact that there should only been the single element. Although id="orders" is most definitely not specific enough to be used as an id :).
