### ISSUE TITLE
HTML needs to be more semantic

### ISSUE THREAD

**Issue by olivierobert** [ericparklondon/nimbl3#6]
HTML has lots of tags to choose from but all I can see is `div`s 😭 

![eric_park](https://user-images.githubusercontent.com/696529/41532510-8190506a-7321-11e8-9424-eba727e19cbc.png)

`<header>` would be a better choice.

![eric_park](https://user-images.githubusercontent.com/696529/41532866-e4809490-7322-11e8-86c0-fce47bfdbd86.png)

How about using `<form>` since an `<input>` is needed for the search?

**Comment by ericparklondon** [comment]
very good point. Although there will always be lots of div tags :)
