### ISSUE TITLE
Avoid empty div to generate styling, instead prefer pseudo selector

### ISSUE THREAD

**Issue by olivierobert** [ericparklondon/nimbl3#7]
![eric_park](https://user-images.githubusercontent.com/696529/41533003-6651d33a-7323-11e8-95dd-0f872383387b.png)

In order to achieve visual details, prefer using pseudo selectors like `:before` or `:after` instead of having empty `div`s as `) it's not semantic and 2) it's wasteful since it can achieved only with CSS.

**Comment by ericparklondon** [comment]
Thank you, good catch.
